### ISSUE TITLE
Implement Workflow Execution Tracking and History

### ISSUE THREAD

**Issue by teemow** [giantswarm/muster#16]
# User Story

As a user of the muster platform, I want to see the actual executions of workflows so that I can:
- Track what workflows have been executed and when
- Debug failed workflow executions by examining step-by-step results
- Audit workflow execution history for compliance and monitoring
- Understand the performance characteristics of my workflows

## Requirements

The user should be able to:
- List workflow executions with filtering and pagination
- Get the complete state of a workflow execution (overall status, current step, results)
- Get the result of a specific step within a workflow execution
- View execution history for debugging and auditing purposes

### Architecture
- **Maintain API Service Locator Pattern**: All functionality must go through the central API layer
- **Use Existing Patterns**: Follow the established patterns used by other core API tools
- **Backwards Compatibility**: Existing `workflow_<name>` tools must continue to work unchanged

### Implementation Details
- **Synchronous Execution Only**: Workflows execute synchronously and return results immediately
- **Automatic Tracking**: Every workflow execution via `workflow_<name>` tools should automatically create an execution record
- **Persistence**: Execution history should be persisted to survive system restarts
- **Performance**: Consider storage limits and cleanup policies for historical data

### User Experience
- **Unified API**: Single endpoint for getting execution details, step results, or summaries
- **Simple Filtering**: Basic filtering by workflow name and status
- **Efficient Pagination**: Support for large execution histories

## What NOT to Implement

- **Asynchronous Execution**: No async workflow execution (workflows remain synchronous)
- **Cancellation**: No ability to cancel running workflows
- **Retry Mechanisms**: No built-in retry functionality for failed executions
- **Real-time Monitoring**: No WebSocket/SSE for live execution updates
- **Complex State Management**: No workflow state persistence during execution

## New API Schema

```json
{
  "core_workflow_execution_list": {
    "description": "Parameters for core_workflow_execution_list tool",
    "properties": {
      "workflow_name": {
        "description": "Filter executions by workflow name (optional)",
        "type": "string"
      },
      "status": {
        "description": "Filter executions by status (optional)",
        "enum": ["completed", "failed"],
        "type": "string"
      },
      "limit": {
        "description": "Maximum number of executions to return (default: 50)",
        "type": "integer",
        "default": 50,
        "minimum": 1,
        "maximum": 1000
      },
      "offset": {
        "description": "Number of executions to skip for pagination (default: 0)",
        "type": "integer",
        "default": 0,
        "minimum": 0
      }
    },
    "type": "object"
  },
  "core_workflow_execution_get": {
    "description": "Parameters for core_workflow_execution_get tool",
    "properties": {
      "execution_id": {
        "description": "Unique identifier of the workflow execution",
        "type": "string"
      },
      "include_steps": {
        "description": "Include detailed step results in the response (default: true)",
        "type": "boolean",
        "default": true
      },
      "step_id": {
        "description": "Get result for specific step only (optional)",
        "type": "string"
      }
    },
    "required": ["execution_id"],
    "type": "object"
  }
}
```

### WorkflowExecution Response Structure
```json
{
  "execution_id": "uuid-string",
  "workflow_name": "deploy-service",
  "status": "completed|failed",
  "started_at": "2024-01-01T00:00:00Z",
  "completed_at": "2024-01-01T00:05:00Z",
  "duration_ms": 300000,
  "input": {
    "service_name": "api",
    "environment": "prod"
  },
  "result": {
    "deployment_id": "deploy-123",
    "status": "success"
  },
  "error": null,
  "steps": [
    {
      "step_id": "validate-config",
      "tool": "core_service_validate",
      "status": "completed",
      "started_at": "2024-01-01T00:00:00Z",
      "completed_at": "2024-01-01T00:00:30Z",
      "duration_ms": 30000,
      "input": {"service_name": "api"},
      "result": {"valid": true},
      "error": null,
      "stored_as": "validation_result"
    }
  ]
}
```

## Example BDD Scenario

```yaml
name: "workflow-execution-tracking"
category: "behavioral"
concept: "workflow"
tags: ["workflow", "execution", "tracking", "history"]
timeout: "3m"

steps:
- id: "create-tracking-workflow"
  tool: "core_workflow_create"
  args:
    name: "tracking-test-workflow"
    inputSchema:
      type: "object"
      properties:
        service_name:
          type: "string"
          description: "Name of the service"
          default: "test-service"
      required: []
    steps:
      - id: "list_services"
        tool: "core_service_list"
        store: "services_result"
      - id: "get_config"
        tool: "core_config_get"
        store: "config_result"
  expected:
    success: true
  cleanup:
    - tool: "core_workflow_delete"
      args: { name: "tracking-test-workflow" }

- id: "execute-workflow-first-time"
  tool: "workflow_tracking-test-workflow"
  args:
    service_name: "api-service"
  expected:
    success: true
  store: "first_execution"

- id: "execute-workflow-second-time"
  tool: "workflow_tracking-test-workflow"
  args:
    service_name: "web-service"
  expected:
    success: true
  store: "second_execution"

- id: "list-all-executions"
  tool: "core_workflow_execution_list"
  args:
    limit: 10
  expected:
    success: true
    contains: ["execution_id", "workflow_name", "status"]

- id: "list-executions-by-workflow"
  tool: "core_workflow_execution_list"
  args:
    workflow_name: "tracking-test-workflow"
    limit: 5
  expected:
    success: true
    contains: ["tracking-test-workflow"]

- id: "get-first-execution-details"
  tool: "core_workflow_execution_get"
  args:
    execution_id: "{{ first_execution.execution_id }}"
  expected:
    success: true
    contains: ["steps", "list_services", "get_config", "duration_ms"]

- id: "get-execution-summary-only"
  tool: "core_workflow_execution_get"
  args:
    execution_id: "{{ first_execution.execution_id }}"
    include_steps: false
  expected:
    success: true
    not_contains: ["steps"]

- id: "get-specific-step-result"
  tool: "core_workflow_execution_get"
  args:
    execution_id: "{{ first_execution.execution_id }}"
    step_id: "list_services"
  expected:
    success: true
    contains: ["step_id", "list_services", "result"]

- id: "get-non-existent-execution"
  tool: "core_workflow_execution_get"
  args:
    execution_id: "non-existent-id"
  expected:
    success: false
    error_contains: ["not found"]

- id: "get-non-existent-step"
  tool: "core_workflow_execution_get"
  args:
    execution_id: "{{ first_execution.execution_id }}"
    step_id: "non-existent-step"
  expected:
    success: false
    error_contains: ["step not found"]
```

### Core Functionality
- [ ] **Automatic Tracking**: Every workflow execution via `workflow_<name>` tools creates an execution record
- [ ] **Execution Listing**: `core_workflow_execution_list` returns paginated list of executions
- [ ] **Execution Details**: `core_workflow_execution_get` returns complete execution information
- [ ] **Step Results**: Individual step results are accessible via `step_id` parameter
- [ ] **Filtering**: Executions can be filtered by `workflow_name` and `status`
- [ ] **Pagination**: List endpoint supports `limit` and `offset` parameters

### Data Integrity
- [ ] **Unique IDs**: Each execution has a unique `execution_id`
- [ ] **Timestamps**: Accurate `started_at` and `completed_at` timestamps
- [ ] **Duration Tracking**: Execution and step durations are recorded in milliseconds
- [ ] **Status Tracking**: Execution status is accurately tracked (`completed`, `failed`)
- [ ] **Input/Output Capture**: Workflow inputs and results are stored
- [ ] **Error Handling**: Failed executions capture error information

### API Consistency
- [ ] **Service Locator Pattern**: Implementation follows architectural guidelines
- [ ] **Error Responses**: Consistent error handling and messaging
- [ ] **Schema Validation**: All API parameters are validated according to schema
- [ ] **Backwards Compatibility**: Existing workflow execution tools continue to work

### Performance & Storage
- [ ] **Efficient Queries**: List operations perform well with large execution histories
- [ ] **Storage Management**: Consider cleanup policies for old execution records
- [ ] **Memory Usage**: Execution tracking doesn't significantly impact workflow performance

### Testing
- [ ] **Unit Tests**: Core execution tracking logic is unit tested (≥80% coverage)
- [ ] **Integration Tests**: BDD scenario passes completely
- [ ] **Error Scenarios**: Edge cases and error conditions are tested
- [ ] **Performance Tests**: Large execution history doesn't degrade performance

### Documentation
- [ ] **API Documentation**: New tools are documented in schema.json
- [ ] **Code Documentation**: All exported functions have GoDoc comments
- [ ] **Architecture Documentation**: Implementation follows documented patterns

### Files to Create/Modify
- `internal/api/handlers.go` - Add WorkflowExecutionHandler interface
- `internal/workflow/execution_tracker.go` - New execution tracking logic
- `internal/workflow/api_adapter.go` - Extend with execution tracking endpoints
- `internal/workflow/storage.go` - Execution persistence layer
- `internal/testing/scenarios/workflow-execution-tracking.yaml` - BDD scenario
- `schema.json` - Will be auto-generated via `muster test --generate-schema`

### Dependencies
- Execution tracking integrates with existing workflow execution flow
- Uses existing config storage patterns for persistence
- Follows established API service locator pattern
